version: '3.9'

services:

  jobs:
    container_name: jobs
    build:
      context: ../jobs
      dockerfile: Dockerfile
    environment:
      - G10_DB_HOST=10.93.240.3
      - G10_DB_PORT=5432
      - G10_REDIS_HOST=10.128.0.7
    networks:
      redproyecto:
        ipv4_address: 10.130.13.3

volumes:

  uploads-volume:
  processed-volume:
  redis-data:
  postgres-data:

networks:

  redproyecto:
    ipam:
      driver: default
      config:
        - subnet: '10.130.13.0/28'