version: '3.9'

services:

#  api:
#    container_name: api
#    build:
#      context: ../api
#      dockerfile: Dockerfile
#    ports:
#      - '3000:5000'
#    networks:
#      redproyecto:
#        ipv4_address: 10.130.13.2
#    volumes:
#      - uploads-volume:/app/uploads
#      - processed-volume:/app/processed
#    depends_on:
#      - 'custom-postgres'

  jobs:
    container_name: jobs
    build:
      context: ../jobs
      dockerfile: Dockerfile
    environment:
      - G10_DB_HOST=10.93.240.3
      - G10_DB_PORT=5432
      - G10_REDIS_HOST=10.128.0.7
    networks:
      redproyecto:
        ipv4_address: 10.130.13.3
    volumes:
      - /tmp/uploads:/app/uploads
      - /tmp/processed:/app/processed

#  custom-redis:
#    container_name: custom-redis
#    build:
#      context: ../custom-redis
#      dockerfile: Dockerfile
#    ports:
#      - '6379:6379'
#    networks:
#      redproyecto:
#        ipv4_address: 10.130.13.4
#    volumes:
#      - redis-data:/data

#  redis-commander:
#    container_name: redis-commander
#    image: ghcr.io/joeferner/redis-commander:latest
#    restart: always
#    environment:
#      - REDIS_HOSTS=local:redis:6379:0:lOGleSPirDOLEYsiceWlemPtO
#    ports:
#      - '8082:8081'
#    networks:
#      redproyecto:
#        ipv4_address: 10.130.13.5
#    depends_on:
#      - 'custom-redis'

#  custom-postgres:
#    container_name: custom-postgres
#    build:
#      context: ../custom-postgres
#      dockerfile: Dockerfile
#    ports:
#      - "5433:5432"
#    networks:
#      redproyecto:
#        ipv4_address: 10.130.13.6
#    volumes:
##      - postgres-data:/var/lib/postgresql/data
#      - ./data:/var/lib/postgresql/data
#
#  custom-nginx:
#    container_name: custom-nginx
#    build:
#      context: ../custom-nginx
#      dockerfile: Dockerfile
#    ports:
#      - '8888:8888'
#    networks:
#      redproyecto:
#        ipv4_address: 10.130.13.7
#    depends_on:
#      - 'api'

volumes:

  uploads-volume:
  processed-volume:
  redis-data:
  postgres-data:

networks:

  redproyecto:
    ipam:
      driver: default
      config:
        - subnet: '10.130.13.0/28'