version: '3.1'

services:

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - uploads-volume:/app/uploads

  jobs:
    build:
      context: ../jobs
      dockerfile: Dockerfile
    volumes:
      - uploads-volume:/app/uploads

  custom-redis:
    build:
      context: ../custom-redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0:lOGleSPirDOLEYsiceWlemPtO
    ports:
      - '8081:8081'
    depends_on:
      - 'redis'

volumes:

  uploads-volume:
  redis-data: