version: '3.9'

services:

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      red-proyecto:
        ipv4_address: 10.130.13.2
    volumes:
      - uploads-volume:/app/uploads

  jobs:
    build:
      context: ../jobs
      dockerfile: Dockerfile
    networks:
      red-proyecto:
        ipv4_address: 10.130.13.3
    volumes:
      - uploads-volume:/app/uploads

  custom-redis:
    build:
      context: ../custom-redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
    networks:
      red-proyecto:
        ipv4_address: 10.130.13.4
    volumes:
      - redis-data:/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0:lOGleSPirDOLEYsiceWlemPtO
    ports:
      - '8082:8081'
    networks:
      red-proyecto:
        ipv4_address: 10.130.13.5
    depends_on:
      - 'custom-redis'

  custom-nginx:
    build:
      context: ../custom-nginx
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    networks:
      red-proyecto:
        ipv4_address: 10.130.13.6
    depends_on:
      - 'api'
      - 'redis-commander'

volumes:

  uploads-volume:
  redis-data:

networks:

  red-proyecto:
    ipam:
      driver: default
      config:
        - subnet: '10.130.13.0/28'