version: '3.9'

services:

  api:
    container_name: api
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/api:${G10_TAG_VERSION:-latest}
    user: 'nobody:nogroup'
    env_file:
      - api.env
    ports:
      - '3000:5000'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.2
    volumes:
      - /nfs/general/uploads:/app/uploads
      - /nfs/general/processed:/app/processed

  jobs:
    container_name: jobs
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/jobs:${G10_TAG_VERSION:-latest}
    user: 'nobody:nogroup'
    env_file:
      - jobs.env
    networks:
      redproyecto:
        ipv4_address: 10.130.13.3
    volumes:
      - /nfs/general/uploads:/app/uploads
      - /nfs/general/processed:/app/processed

  custom-redis:
    container_name: custom-redis
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/custom-redis:${G10_TAG_VERSION:-latest}
    ports:
      - '6379:6379'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.4

  custom-locust:
    container_name: custom-locust
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/custom-locust:${G10_TAG_VERSION:-latest}
    env_file:
      - custom-locust.env
    ports:
      - '8089:8089'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.5

  custom-postgres:
    container_name: custom-postgres
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/custom-postgres:${G10_TAG_VERSION:-latest}
    ports:
      - "5433:5432"
    networks:
      redproyecto:
        ipv4_address: 10.130.13.6

  custom-nginx:
    container_name: custom-nginx
    image: ghcr.io/je-guerreroa1-uniandes/grupo-10-nube/custom-nginx:${G10_TAG_VERSION:-latest}
    ports:
      - '8888:8888'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.7
    depends_on:
      - 'api'

networks:

  redproyecto:
    ipam:
      driver: default
      config:
        - subnet: '10.130.13.0/28'