version: '3.9'

services:

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      - G10_DB_HOST=10.93.240.3
      - G10_DB_PORT=5432
      - G10_REDIS_HOST=10.128.0.7
    ports:
      - '3000:5000'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.2

  custom-nginx:
    container_name: custom-nginx
    build:
      context: ../custom-nginx
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    networks:
      redproyecto:
        ipv4_address: 10.130.13.7
    depends_on:
      - 'api'

volumes:

  uploads-volume:
  processed-volume:
  redis-data:
  postgres-data:

networks:

  redproyecto:
    ipam:
      driver: default
      config:
        - subnet: '10.130.13.0/28'