# Python 3.7, 3.8, and 3.9 run on Ubuntu 18.04
# Python 3.10 and 3.11 run on Ubuntu 22.04
runtime: python39

service: jobs # This service name is used in the URL for the service. {'default', 'jobs'}

instance_class: B2 # (default instance class) Number of workers=4, Memory Limit=768MB, CPU Limit=1.2GHz 

basic_scaling:
  max_instances: 5
  idle_timeout: 10m

# Con este include podemos declarar variables de entorno en un archivo aparte
# y dejarlo por fuera del repositorio con el .gitignore
includes:
  - env_variables.yaml

handlers:
- url: /.*
  secure: always # OJO: Este puede que toque comentarlo
  redirect_http_response_code: 301
  script: auto

entrypoint: python -m worker