# Python 3.7, 3.8, and 3.9 run on Ubuntu 18.04
# Python 3.10 and 3.11 run on Ubuntu 22.04
runtime: python39

service: api # This service name is used in the URL for the service. {'api', 'jobs'}

instance_class: B2 # (default instance class) Number of workers=4, Memory Limit=768MB, CPU Limit=1.2GHz 

basic_scaling:
  max_instances: 5
  idle_timeout: 10m

#env_variables: # Este bloque se usa para definir variables de entorno.
#  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /.*
  secure: always # OJO: Este puede que toque comentarlo
  redirect_http_response_code: 301
  script: auto
  http_headers:
    Access-Control-Allow-Origin: '*'

entrypoint: gunicorn -b :$PORT -w 4 wsgi:app