# Python 3.7, 3.8, and 3.9 run on Ubuntu 18.04
# Python 3.10 and 3.11 run on Ubuntu 22.04
runtime: python39

# The first service (module) you upload to a new application must be the 'default' service (module).
# Please upload a version of the 'default' service (module) before uploading a version for the 'api' service
service: default

instance_class: B2 # (default instance class) Number of workers=4, Memory Limit=768MB, CPU Limit=1.2GHz 

basic_scaling:
  max_instances: 5
  idle_timeout: 10m

env_variables: # Este bloque se usa para definir variables de entorno.
  G10_DB_PREFIX: "postgresql"
  G10_DB_USERNAME: "converter_db"
  G10_DB_PASSWORD: "ckhAMLIteFlYheRptAteapeze"
  G10_DB_HOST: "34.71.6.228"
  G10_DB_PORT: "5432"
  G10_DB_DBNAME: "conversion"

handlers:
- url: /.*
  secure: always # OJO: Este puede que toque comentarlo
  redirect_http_response_code: 301
  script: auto

entrypoint: gunicorn -b :$PORT -w 4 wsgi:app